name: Dev Destroy

on:
  workflow_dispatch:

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install python dev dependencies
        run: pip install --target ./src -r ./software/requirements-dev.txt

      - name: Install python infrastructure dependencies
        run: pip install -r ./infra/requirements-infra.txt

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: install aws cdk
        run: npm install -g aws-cdk

      - name: Install web depencies for lambda
        run: npm install xhr2

      - name: Configure AWS Credentials (Raw ACcount)
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::783978466054:role/GitHubOIDCRole
          aws-region: us-east-1

      - name: cdk synth
        run: cdk synth aws-common-services-stack

      - name: cdk destroy
        run: cdk destroy aws-common-services-stack --require-approval never --force
